# Generated by Django 5.1.4 on 2024-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sizecolor',
            name='product_color_image',
            field=models.ImageField(null=True, upload_to='product_color'),
        ),
    ]
