# Generated by Django 5.1.4 on 2024-12-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_colorvariant_additional_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
