# Generated by Django 5.1.4 on 2024-12-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_colorvariant_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_name',
            field=models.CharField(max_length=100),
        ),
    ]
