# Generated by Django 5.1.4 on 2024-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_color_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product_color_image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ManyToManyField(to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_color_image',
            field=models.ManyToManyField(related_name='product_color_image', to='products.productimage'),
        ),
    ]
