# Generated by Django 5.1.4 on 2024-12-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product_color_image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_color_image',
            field=models.ImageField(null=True, upload_to='product_color_image'),
        ),
    ]
