# Generated by Django 5.1.4 on 2024-12-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color')},
        ),
    ]
