# Generated by Django 5.1.4 on 2024-12-28 13:29

import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizevariant'),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(max_length=100, verbose_name=products.models.Product),
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product_color_image', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
