# Generated by Django 5.1.4 on 2024-12-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_colorvariant_size_sizevariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='product_color_image',
            field=models.ImageField(null=True, upload_to='product_color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product_color_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color_image', to='products.colorvariant'),
        ),
    ]
