# Generated by Django 5.1.4 on 2024-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productcolorimage_product_color_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
